fix missing includes and warning params
Panzerschrek/HexGPU pull request #2
Opened 2024-08-11 17:08 UTC by jopadan

2024-08-11 17:16 UTC, Panzerschrek requested changes

2024-08-11 17:16 UTC, Panzerschrek commented on src/BlockType.hpp
> +enum Direction : uint8_t
It's preferred way to use scoped enums in C++. Why is this change needed?

2024-08-11 17:16 UTC, Panzerschrek commented on src/CMakeLists.txt
> +	add_compile_options(-Werror -Wno-error=conversion -Wno-error=unused-parameter -Wall -Wextra -Wconversion)
What's problem with these errors? Is there any places where such errors are triggered?

2024-08-11 17:16 UTC, Panzerschrek commented on src/ChunksStorage.hpp
> +#include <algorithm>
I see no usage of functions or other stuff from <algorithm> in this header. Consider adding this include only into the file where it's necessary (usually cpp file). Keep also alphabetic order for stdlib includes.

2024-08-11 18:00 UTC, jopadan commented on src/CMakeLists.txt
> +	add_compile_options(-Werror -Wno-error=conversion -Wno-error=unused-parameter -Wall -Wextra -Wconversion)
imgui_impl_vulkan.h: In constructor 'ImGui_ImplVulkanH_Window::ImGui_ImplVulkanH_Window()'
the result of the conversion is unspecified because '~0' is outside the range of type 'VkPresentModeKHR'

unused parameter is triggered by adding standard main arguments

2024-08-11 18:02 UTC, jopadan commented on src/ChunksStorage.hpp
> +#include <algorithm>
`src/ChunksStorage.cpp:79:22 remove_if is not a member of 'std'; did you mean 'remove_cv'`

2024-08-11 18:04 UTC, Panzerschrek commented on src/ChunksStorage.hpp
> +#include <algorithm>
So, you need to add this include into `ChunksStorage.cpp`, instead adding it into the corresponding header.

2024-08-11 18:07 UTC, Panzerschrek commented on src/CMakeLists.txt
> +	add_compile_options(-Werror -Wno-error=conversion -Wno-error=unused-parameter -Wall -Wextra -Wconversion)
So, you have warnings in Vulkan headers.
For such case I have a special wrapper header `HexGPUVulkan.hpp`. You can add specific warnigs suppression code into it, like this:

```cpp
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#endif // __GNUC__

#include <vulkan/vulkan.hpp>

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
```

2024-08-11 18:13 UTC, jopadan commented on src/BlockType.hpp
> +enum Direction : uint8_t
Correct I think this change is unnecessary and the error was triggered because of the missing standard include.

2024-08-11 18:29 UTC, Panzerschrek commented on src/ChunksStorage.cpp
> +#include <algorithm>
Use here alphabetic order for stdlib includes (`algorithm` before `cstring`).

2024-08-11 18:29 UTC, Panzerschrek commented on src/HexGPUVulkan.hpp
> +#pragma diagnostic push
it seems to be wrong pragma. It should be `#pragma GCC diagnostic push`, `#pragma GCC diagnostic ignored`, `#pragma GCC diagnostic pop`.

Sorry, this was my error.

2024-08-11 18:37 UTC, jopadan commented on src/HexGPUVulkan.hpp
Adding the pragmas doesn't silence the warnings.

2024-08-11 18:45 UTC, Panzerschrek commented on src/HexGPUVulkan.hpp
What compiler do you use? GCC (version?), Clang? MSVC? Something else?

What version of VulkanSDK or Vulkan headers?

Maybe you have problems with warnings in other places in code?

2024-08-11 18:47 UTC, Panzerschrek commented on src/HexGPUVulkan.hpp
Damn, now i see it.
You have warnings not in Vulkan headers, but in ImGui headers for Vulkan.

So, you need to move this warning suppression pragmas into `ImGuiWrapper.hpp` - around `imgui` includes.

2024-08-11 18:49 UTC, jopadan commented on src/HexGPUVulkan.hpp
gcc-14.2.1_p20240803 and vulkan-headers-1.3.290.0-r1

2024-08-12 06:01 UTC, Panzerschrek approved these changes

2024-08-12 06:01 UTC, merged